package:
  name: cryptography
  version: "45.0.7"

build:
  # The legacy provider is not available in Chaquopy's OpenSSL build, so tell
  # cryptography not to try loading it.
  script_env:
    - CRYPTOGRAPHY_BUILD_OPENSSL_NO_LEGACY=1

requirements:
  build:
    - rust
  host:
    - openssl
